version: "2"

run:
  timeout: 5m
  tests: false
  modules-download-mode: vendor

linters:
  enable:
    - lll
  disable:
    # TODO: remove these two and fix all the lint errors
    - errcheck
    - staticcheck
  settings:
    lll:
      line-length: 120
  exclusions:
    rules:
      - path: internal/databox/blob.go
        linters:
          - lll
