# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/v1/cdk.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/v1/cdk.proto\x12\x03\x63\x64k\"%\n\x0bPingRequest\x12\x16\n\x0e\x63omponent_name\x18\x01 \x01(\t\"\x1c\n\tPongReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x07\n\x05Reply\"\xb9\x01\n\x10HoneyventRequest\x12\x0f\n\x07\x66\x65\x61ture\x18\x01 \x01(\t\x12<\n\x0c\x66\x65\x61ture_data\x18\x02 \x03(\x0b\x32&.cdk.HoneyventRequest.FeatureDataEntry\x12\r\n\x05\x65rror\x18\x03 \x01(\t\x12\x13\n\x0b\x64uration_ms\x18\x04 \x01(\x03\x1a\x32\n\x10\x46\x65\x61tureDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\x63\n\x03\x43\x44K\x12*\n\x04Ping\x12\x10.cdk.PingRequest\x1a\x0e.cdk.PongReply\"\x00\x12\x30\n\tHoneyvent\x12\x15.cdk.HoneyventRequest\x1a\n.cdk.Reply\"\x00\x42&Z$lacework/go-sdk/cli/cdk/proto/v1;cdkb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.v1.cdk_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z$lacework/go-sdk/cli/cdk/proto/v1;cdk'
  _HONEYVENTREQUEST_FEATUREDATAENTRY._options = None
  _HONEYVENTREQUEST_FEATUREDATAENTRY._serialized_options = b'8\001'
  _PINGREQUEST._serialized_start=27
  _PINGREQUEST._serialized_end=64
  _PONGREPLY._serialized_start=66
  _PONGREPLY._serialized_end=94
  _REPLY._serialized_start=96
  _REPLY._serialized_end=103
  _HONEYVENTREQUEST._serialized_start=106
  _HONEYVENTREQUEST._serialized_end=291
  _HONEYVENTREQUEST_FEATUREDATAENTRY._serialized_start=241
  _HONEYVENTREQUEST_FEATUREDATAENTRY._serialized_end=291
  _CDK._serialized_start=293
  _CDK._serialized_end=392
# @@protoc_insertion_point(module_scope)
