// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: proto/v1/cdk.proto

package cdk

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CDKClient is the client API for CDK service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CDKClient interface {
	// Sends a ping -> pong between server and client
	//    Component -> CDK Server
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PongReply, error)
	// Sends a Honeyvent
	Honeyvent(ctx context.Context, in *HoneyventRequest, opts ...grpc.CallOption) (*Reply, error)
}

type cDKClient struct {
	cc grpc.ClientConnInterface
}

func NewCDKClient(cc grpc.ClientConnInterface) CDKClient {
	return &cDKClient{cc}
}

func (c *cDKClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PongReply, error) {
	out := new(PongReply)
	err := c.cc.Invoke(ctx, "/cdk.CDK/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDKClient) Honeyvent(ctx context.Context, in *HoneyventRequest, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/cdk.CDK/Honeyvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CDKServer is the server API for CDK service.
// All implementations must embed UnimplementedCDKServer
// for forward compatibility
type CDKServer interface {
	// Sends a ping -> pong between server and client
	//    Component -> CDK Server
	Ping(context.Context, *PingRequest) (*PongReply, error)
	// Sends a Honeyvent
	Honeyvent(context.Context, *HoneyventRequest) (*Reply, error)
	mustEmbedUnimplementedCDKServer()
}

// UnimplementedCDKServer must be embedded to have forward compatible implementations.
type UnimplementedCDKServer struct {
}

func (UnimplementedCDKServer) Ping(context.Context, *PingRequest) (*PongReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedCDKServer) Honeyvent(context.Context, *HoneyventRequest) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Honeyvent not implemented")
}
func (UnimplementedCDKServer) mustEmbedUnimplementedCDKServer() {}

// UnsafeCDKServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CDKServer will
// result in compilation errors.
type UnsafeCDKServer interface {
	mustEmbedUnimplementedCDKServer()
}

func RegisterCDKServer(s grpc.ServiceRegistrar, srv CDKServer) {
	s.RegisterService(&CDK_ServiceDesc, srv)
}

func _CDK_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDKServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cdk.CDK/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDKServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDK_Honeyvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HoneyventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDKServer).Honeyvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cdk.CDK/Honeyvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDKServer).Honeyvent(ctx, req.(*HoneyventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CDK_ServiceDesc is the grpc.ServiceDesc for CDK service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CDK_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cdk.CDK",
	HandlerType: (*CDKServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _CDK_Ping_Handler,
		},
		{
			MethodName: "Honeyvent",
			Handler:    _CDK_Honeyvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/v1/cdk.proto",
}
