Vagrant.configure("2") do |config|
  config.vm.box = "jhcook/macos-sierra"

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--usb", "on"]
    vb.customize ["modifyvm", :id, "--usbehci", "off"]
  end

  config.vm.network "private_network", ip: "192.168.50.4"
  config.vm.synced_folder "../../../bin", "/devcli", type: "nfs"

  config.vm.provision "shell", inline: "ln -s /devcli/lacework-cli-darwin-amd64 /home/vagrant/lacework"
end
