#!/bin/bash
#
# Name::        version_updater.sh
# Description:: Generates 'version.go' files to be loaded in Go libraries
#               based of the 'VERSION' file at the root of this repository
# Author::      Salim Afiune Maya (<afiune@lacework.net>)
#
set -eou pipefail

VERSION=$(cat VERSION)
TIMESTAMP=$(date +%Y%m%d%H%M%S)

# List of libraries that need the version of this reporitory in Go code
readonly libraries=(api)

for lib in "${libraries[@]}"; do
  echo "Updating ${lib}/version.go"
  cat <<EOF > ${lib}/version.go
// Code generated by: scripts/version_updater.sh
// File generated at: $TIMESTAMP
//
// <<< DO NOT EDIT >>>
//

package $lib

// Version is the semver coming from the VERSION file
const Version = "$VERSION"
EOF
done
