#!/bin/bash
readonly project_name=go-sdk
readonly commit_tags="feat(:|\(.*\):)|fix(:|\(.*\):)|style(:|\(.*\):)|refactor(:|\(.*\):)\|test(:|\(.*\):)\|docs(:|\(.*\):)\|chore(:|\(.*\):)\|build(:|\(.*\):)\|ci(:|\(.*\):)\|perf(:|\(.*\):)\|metric(:|\(.*\):)\|misc(:|\(.*\):)"
readonly commit_message=`cat $1`
readonly blah="Please enter the commit message for your changes"

validate_commit_message(){
        if ! [[ $commit_message =~ $commit_tags ]]; then
            invalid_message
            exit 1
        fi
            log "Commit message is valid"
} 

invalid_message(){
    log "Invalid commit message"
    log "Message must contain one of feat: | fix: | style: | refactor: | test: | docs: | chore: | build: | ci: | perf: | metric: | misc:
      Or with scope in parenthesis eg. feat(cli): Add new feature"
}

log() {
  echo "--> ${project_name}: $1"
}

validate_commit_message

