// Code generated by: scripts/version_updater.sh
// File generated at: 20250328195455
//
// <<< DO NOT EDIT >>>
//

package api

// Version is the semver coming from the VERSION file
const Version = "2.1.7"
