// Code generated by: scripts/version_updater.sh
// File generated at: 20230317184642
//
// <<< DO NOT EDIT >>>
//

package api

// Version is the semver coming from the VERSION file
const Version = "1.14.1-dev"
