// Code generated by: scripts/version_updater.sh
// File generated at: 20220310202010
//
// <<< DO NOT EDIT >>>
//

package api

// Version is the semver coming from the VERSION file
const Version = "0.27.1-dev"
