name: Commit Message Lint
on:
  pull_request:
    branches: [ "main" ]

jobs:
  gitlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Install gitlint
        shell: bash
        run: |
          python -m pip install gitlint

      - name: Run gitlint
        shell: bash
        run: |
          gitlint --commit ${{ github.event.pull_request.head.sha }} --debug